name: On Pull Request

on:
  pull_request:
    branches:
      - main
      - QA
      - dev

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Npm Install
        run: npm install

      - name:  Install Angular
        run: npm install -g @angular/cli

      - name: Run Tests
        run: npm test

  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker
        uses: docker/setup-buildx-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build
        run: docker build -t ghcr.io/${{ github.repository }}:${{github.ref_name}}.docker push ghcr.io/${{github.repository}}:${{github.ref_name}}
