name: On Pull Request

on:
  pull_request:
    branches:
      - main
      - QA
      - dev

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Npm Install
        run: npm install

      - name:  Install Angular
        run: npm install -g @angular/cli

      - name: Run Tests
        run: npm test

  build:
    if: github.event.pull_request.merged == true  
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker
        uses: docker/setup-buildx-action@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.PAT }}

      - name: Build image
        run: |
          docker build -t ghcr.io/juliangonzalezcanas/cicd-front-gonzalez-carone/constainer:latest
      - name: Push image
        run: |
          docker push ghcr.io/juliangonzalezcanas/cicd-front-gonzalez-carone/constainer:latest
