name: On Pull Request

on:
  pull_request:
    branches:
      - main
      - QA
      - dev

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Npm Install
        run: npm install

      - name:  Install Angular
        run: npm install -g @angular/cli

      - name: Run Tests
        run: npm test

  deploy:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@master
      - name: docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/container
          tags: latest, ${{github.run_number}}
